version: "3"
services:
  yh-redis:
    image: redis:7.0.4-alpine3.16
    configs:
      - source: redis-config
        target: /usr/local/etc/redis/redis.conf
        uid: '999'
        gid: '1000'
        mode: 0644
    command:
      - "redis-server"
      - "/usr/local/etc/redis/redis.conf"
    network_mode: bridge
    ports:
      - "6379:6379"
    volumes:
      - "yh-redis-data:/data"
    restart: "no"

configs:
  redis-config:
    file: redis.conf

volumes:
  yh-redis-data:
    driver: local
