version: '3'
services:
  mariadb:
    image: "bitnami/mariadb:10.5.9"
    environment:
      MARIADB_ROOT_USER: "root"   # 超级管理员账号名
      MARIADB_ROOT_PASSWORD: "123456"   # 超级管理员密码
      MARIADB_AUTHENTICATION_PLUGIN: "mysql_native_password"   # 认证插件
      MARIADB_CHARACTER_SET: "utf8"   # 默认字符集（服务器级别）
      MARIADB_COLLATE: "utf8_general_ci"   # 默认排序规则（服务器级别）
      MARIADB_ENABLE_SLOW_QUERY: 0   # 是否开启慢查询，0：不开启  1：开启
      MARIADB_LONG_QUERY_TIME: 5.0   # 慢查询超时时间
    network_mode: bridge
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: yh_mariadb_data
        target: /bitnami/mariadb
      - type: volume
        source: yh_mariadb_conf
        target: /opt/bitnami/mariadb/conf
    restart: "no"

volumes:
  yh_mariadb_data: {}
  yh_mariadb_conf: {}