version: '3'
services:
  zabbix-proxy-mysql:
      image: bitnami/mysql:8.0.30
      environment:
        MYSQL_ROOT_USER: "root"   # 管理员账户名
        MYSQL_ROOT_PASSWORD: "123456"   # 管理员密码
        MYSQL_DATABASE: "zabbix_proxy"
        MYSQL_USER: "zabbix_proxy"
        MYSQL_PASSWORD: "zabbix_proxy"
        MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
        MYSQL_CHARACTER_SET: utf8
        MYSQL_COLLATE: utf8_bin
        BITNAMI_DEBUG: "true"
      volumes:
        - "zabbix-proxy-mysql-data:/bitnami/mysql/data"
      networks:
        - "zabbix-proxy-network"
  zabbix-proxy:
    depends_on:
      - "zabbix-proxy-mysql"
    image: "zabbix/zabbix-proxy-mysql:6.0-alpine-latest"
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: "zabbix-proxy-mysql"
      DB_SERVER_PORT: 3306
      MYSQL_USER: "zabbix_proxy"
      MYSQL_PASSWORD: "zabbix_proxy"
      MYSQL_DATABASE: "zabbix_proxy"
      ZBX_PROXYMODE: 0
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER_PORT: 10051
      ZBX_CONFIGFREQUENCY: 300
      ZBX_DATASENDERFREQUENCY: 1
    networks:
      - "zabbix-proxy-network"


volumes:
  zabbix-proxy-mysql-data: {}
networks:
  zabbix-proxy-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/29
