version: '3'

services:
  yhwms_zookeeper:
    image: 'harbor-xili.yhglobal.cn/docker-compose/zookeeper:3.8.0-debian-10-r37'
    container_name: yhwms_zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_SERVER_ID: 1
  yhwms_kafka1:
    image: 'harbor-xili.yhglobal.cn/docker-compose/kafka:3.1.1-debian-10-r0'
    container_name: yhwms_kafka1
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: yhwms_zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://yhwms_kafka1:9092,EXTERNAL://127.0.0.1:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xms100m -Xmx500m"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES: "10000"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS: "1000"
      KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824"
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS: "300000"
      KAFKA_CFG_LOG_RETENTION_HOURS: "168"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "10000120"
      KAFKA_CFG_LOG_SEGMENT_BYTES: "1073741824"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_NUM_IO_THREADS: "8"
      KAFKA_CFG_NUM_NETWORK_THREADS: "3"
      KAFKA_CFG_NUM_PARTITIONS: "3"
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: "1"
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: "104857600"
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: "102400"
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "6000"
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: ""
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CFG_SUPER_USERS: "User:admin"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION: "false"
    ports:
      - 9093:9093
    depends_on:
      - yhwms_zookeeper
  yhwms_kafka2:
    image: 'harbor-xili.yhglobal.cn/docker-compose/kafka:3.1.1-debian-10-r0'
    container_name: yhwms_kafka2
    restart: always
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: yhwms_zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://yhwms_kafka2:9092,EXTERNAL://127.0.0.1:9094
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xms100m -Xmx500m"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES: "10000"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS: "1000"
      KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824"
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS: "300000"
      KAFKA_CFG_LOG_RETENTION_HOURS: "168"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "10000120"
      KAFKA_CFG_LOG_SEGMENT_BYTES: "1073741824"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_NUM_IO_THREADS: "8"
      KAFKA_CFG_NUM_NETWORK_THREADS: "3"
      KAFKA_CFG_NUM_PARTITIONS: "3"
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: "1"
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: "104857600"
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: "102400"
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "6000"
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: ""
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CFG_SUPER_USERS: "User:admin"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION: "false"
    ports:
      - 9094:9094
    depends_on:
      - yhwms_zookeeper
  yhwms_kafka3:
    image: 'harbor-xili.yhglobal.cn/docker-compose/kafka:3.1.1-debian-10-r0'
    container_name: yhwms_kafka3
    restart: always
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: yhwms_zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,EXTERNAL://:9095
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://yhwms_kafka3:9092,EXTERNAL://localhost:9095
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xms100m -Xmx500m"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES: "10000"
      KAFKA_CFG_LOG_FLUSH_INTERVAL_MS: "1000"
      KAFKA_CFG_LOG_RETENTION_BYTES: "1073741824"
      KAFKA_CFG_LOG_RETENTION_CHECK_INTERVALS_MS: "300000"
      KAFKA_CFG_LOG_RETENTION_HOURS: "168"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "10000120"
      KAFKA_CFG_LOG_SEGMENT_BYTES: "1073741824"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "3"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_CFG_NUM_IO_THREADS: "8"
      KAFKA_CFG_NUM_NETWORK_THREADS: "3"
      KAFKA_CFG_NUM_PARTITIONS: "3"
      KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR: "1"
      KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES: "102400"
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: "104857600"
      KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES: "102400"
      KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS: "6000"
      KAFKA_CFG_AUTHORIZER_CLASS_NAME: ""
      KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CFG_SUPER_USERS: "User:admin"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"
      KAFKA_CFG_UNCLEAN_LEADER_ELECTION: "false"
    ports:
      - 9095:9095
    depends_on:
      - yhwms_zookeeper
  yhwms_kafkaui:
    image: 'harbor-xili.yhglobal.cn/docker-compose/kafka-ui:v0.6.0'
    container_name: yhwms_kafkaui
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: yhwms_kafka3:9092
    ports:
      - 8088:8080
    depends_on:
      - yhwms_kafka1
      - yhwms_kafka2
      - yhwms_kafka3
